import 'models/chat_three_model.dart';import 'package:flutter/material.dart';import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/app_bar/appbar_leading_image.dart';import 'package:nofapp/widgets/app_bar/appbar_title_searchview.dart';import 'package:nofapp/widgets/app_bar/custom_app_bar.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_icon_button.dart';import 'package:nofapp/widgets/custom_search_view.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/chat_three_provider.dart';class ChatThreeScreen extends StatefulWidget {const ChatThreeScreen({Key? key}) : super(key: key);

@override ChatThreeScreenState createState() =>  ChatThreeScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ChatThreeProvider(), child: ChatThreeScreen()); } 
 }
class ChatThreeScreenState extends State<ChatThreeScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildSearchStack(context), Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildDateDivider(context), SizedBox(height: 18.v), _buildFrameSixtyOne(context, userName: "msg_john_what_s_up".tr, time: "lbl_12_01".tr), SizedBox(height: 20.v), _buildFrameSixty(context, timeLabel: "lbl_12_01".tr, messageText: "msg_good_i_finally".tr), SizedBox(height: 20.v), _buildFrameSixtyOne(context, userName: "msg_sarah_what_s_up".tr, time: "lbl_12_01".tr), SizedBox(height: 20.v), Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 12.v), child: Text("lbl_12_01".tr, style: theme.textTheme.bodyMedium)), _buildNiceButton(context)])), SizedBox(height: 20.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgImage5, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h), margin: EdgeInsets.symmetric(vertical: 22.v)), _buildFrameFiftyFiveEditText(context), Padding(padding: EdgeInsets.only(left: 8.h, top: 22.v, bottom: 24.v), child: Text("lbl_12_01".tr, style: theme.textTheme.bodyMedium))]), SizedBox(height: 20.v), _buildFrameSixty(context, timeLabel: "lbl_12_01".tr, messageText: "msg_good_i_finally".tr), SizedBox(height: 25.v), _buildDateDivider1(context), SizedBox(height: 18.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgImage424x24, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h), margin: EdgeInsets.symmetric(vertical: 22.v)), _buildFrameFiftyNineEditText(context), Padding(padding: EdgeInsets.only(left: 8.h, top: 22.v, bottom: 24.v), child: Text("lbl_12_01".tr, style: theme.textTheme.bodyMedium))]), SizedBox(height: 5.v)]))])), bottomNavigationBar: _buildMessageRow(context))); } 
/// Section Widget
Widget _buildSearchStack(BuildContext context) { return SizedBox(height: 93.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomAppBar(height: 50.v, leadingWidth: 52.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgBackButtonOnerrorcontainer, margin: EdgeInsets.only(left: 20.h, top: 9.v, bottom: 9.v)), title: Selector<ChatThreeProvider, TextEditingController?>(selector: (context, provider) => provider.searchController, builder: (context, searchController, child) {return AppbarTitleSearchview(margin: EdgeInsets.only(left: 12.h), hintText: "lbl_group_name".tr, controller: searchController);})), Align(alignment: Alignment.center, child: Container(width: double.maxFinite, padding: EdgeInsets.all(20.h), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(top: 17.v, bottom: 4.v), onTap: () {onTapImgBackButton(context);}), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, top: 13.v), child: Selector<ChatThreeProvider, TextEditingController?>(selector: (context, provider) => provider.searchController1, builder: (context, searchController1, child) {return CustomSearchView(controller: searchController1, hintText: "lbl_search".tr, contentPadding: EdgeInsets.only(top: 10.v, right: 30.h, bottom: 10.v));})))])))])); } 
/// Section Widget
Widget _buildDateDivider(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 165.h, child: Divider())), Text("lbl_may_29".tr, style: CustomTextStyles.bodySmallGray50001), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 166.h, child: Divider()))]); } 
/// Section Widget
Widget _buildNiceButton(BuildContext context) { return CustomElevatedButton(height: 44.v, width: 71.h, text: "lbl_nice".tr, margin: EdgeInsets.only(left: 10.h), buttonStyle: CustomButtonStyles.fillPrimaryTL10, buttonTextStyle: CustomTextStyles.bodyLargeGray100); } 
/// Section Widget
Widget _buildFrameFiftyFiveEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h), child: Selector<ChatThreeProvider, TextEditingController?>(selector: (context, provider) => provider.frameFiftyFiveEditTextController, builder: (context, frameFiftyFiveEditTextController, child) {return CustomTextFormField(width: 151.h, controller: frameFiftyFiveEditTextController, hintText: "msg_sarah_hey_all_is".tr, borderDecoration: TextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray100);})); } 
/// Section Widget
Widget _buildDateDivider1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 168.h, child: Divider())), Text("lbl_today".tr, style: CustomTextStyles.bodySmallGray50001), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 169.h, child: Divider()))]); } 
/// Section Widget
Widget _buildFrameFiftyNineEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h), child: Selector<ChatThreeProvider, TextEditingController?>(selector: (context, provider) => provider.frameFiftyNineEditTextController, builder: (context, frameFiftyNineEditTextController, child) {return CustomTextFormField(width: 193.h, controller: frameFiftyNineEditTextController, hintText: "msg_sarah_hey_guys_all".tr, borderDecoration: TextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray100);})); } 
/// Section Widget
Widget _buildMessageEditText(BuildContext context) { return Expanded(child: Selector<ChatThreeProvider, TextEditingController?>(selector: (context, provider) => provider.messageEditTextController, builder: (context, messageEditTextController, child) {return CustomTextFormField(controller: messageEditTextController, hintText: "lbl_type_a_message".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineLightBlueA, filled: true, fillColor: theme.colorScheme.onErrorContainer.withOpacity(1));})); } 
/// Section Widget
Widget _buildMessageRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 10.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildMessageEditText(context), Padding(padding: EdgeInsets.only(left: 9.h, top: 5.v, bottom: 5.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.outlineLightBlueA, child: CustomImageView(imagePath: ImageConstant.imgGroup48095863)))])); } 
/// Common widget
Widget _buildFrameSixtyOne(BuildContext context, {required String userName, required String time, }) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgRectangle18, height: 24.adaptSize, width: 24.adaptSize, radius: BorderRadius.circular(12.h), margin: EdgeInsets.symmetric(vertical: 22.v)), Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 8.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_sarah".tr, style: CustomTextStyles.bodyMediumPrimary), TextSpan(text: "msg_what_s_up_dude2".tr, style: CustomTextStyles.bodyLargeBlack90002)]), textAlign: TextAlign.left)])), Padding(padding: EdgeInsets.only(left: 8.h, top: 22.v, bottom: 24.v), child: Text(time, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700)))]); } 
/// Common widget
Widget _buildFrameSixty(BuildContext context, {required String timeLabel, required String messageText, }) { return Row(mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 34.v, bottom: 36.v), child: Text(timeLabel, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700))), Container(margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 9.v), decoration: AppDecoration.primary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL101), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), SizedBox(width: 207.h, child: Text(messageText, maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeGray100.copyWith(color: appTheme.gray100)))]))]); } 
/// Navigates to the chatOneScreen when the action is triggered.
onTapImgBackButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.chatOneScreen, ); } 
 }
