import '../daily_task_three_screen/widgets/exercisecomponentlist_item_widget.dart';import 'models/daily_task_three_model.dart';import 'models/exercisecomponentlist_item_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'provider/daily_task_three_provider.dart';class DailyTaskThreeScreen extends StatefulWidget {const DailyTaskThreeScreen({Key? key}) : super(key: key);

@override DailyTaskThreeScreenState createState() =>  DailyTaskThreeScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => DailyTaskThreeProvider(), child: DailyTaskThreeScreen()); } 
 }
class DailyTaskThreeScreenState extends State<DailyTaskThreeScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildDailyTaskStack(context), SizedBox(height: 24.v), _buildExerciseComponentList(context)])))); } 
/// Section Widget
Widget _buildDailyTaskStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(bottom: 13.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 24.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 33.v, width: 163.h, text: "lbl_daily_task".tr, margin: EdgeInsets.only(bottom: 17.v), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapDailyTask(context);}), CustomImageView(imagePath: ImageConstant.imgMaskGroup24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 3.v, bottom: 24.v), onTap: () {onTapImgImage(context);})])))])); } 
/// Section Widget
Widget _buildExerciseComponentList(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Consumer<DailyTaskThreeProvider>(builder: (context, provider, child) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: provider.dailyTaskThreeModelObj.exercisecomponentlistItemList.length, itemBuilder: (context, index) {ExercisecomponentlistItemModel model = provider.dailyTaskThreeModelObj.exercisecomponentlistItemList[index]; return ExercisecomponentlistItemWidget(model);});}))); } 
/// Navigates to the homeScreen when the action is triggered.
onTapDailyTask(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the dailyTaskTwoScreen when the action is triggered.
onTapImgImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dailyTaskTwoScreen, ); } 
 }
