import 'models/sign_in_model.dart';import 'package:flutter/material.dart';import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_checkbox_button.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_icon_button.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/sign_in_provider.dart';class SignInScreen extends StatefulWidget {const SignInScreen({Key? key}) : super(key: key);

@override SignInScreenState createState() =>  SignInScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SignInProvider(), child: SignInScreen()); } 
 }
class SignInScreenState extends State<SignInScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 23.v), child: Column(children: [Container(height: 120.adaptSize, width: 120.adaptSize, decoration: AppDecoration.primary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder11), child: CustomImageView(imagePath: ImageConstant.imgImage130, height: 120.adaptSize, width: 120.adaptSize, alignment: Alignment.center)), SizedBox(height: 19.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_welcome_back".tr, style: CustomTextStyles.titleLargeBluegray900_1)), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_sign_in".tr, style: CustomTextStyles.titleLargePrimary)), SizedBox(height: 18.v), _buildPhoneNumberSection(context), SizedBox(height: 21.v), _buildPasswordSection(context), SizedBox(height: 21.v), _buildForgotPasswordSection(context), Spacer(), CustomElevatedButton(text: "lbl_sign_in".tr, onPressed: () {onTapSignIn(context);}), SizedBox(height: 29.v), GestureDetector(onTap: () {onTapTxtDonthaveanaccount(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_don_t_have_an_account2".tr, style: CustomTextStyles.bodyLargeBluegray900), TextSpan(text: " "), TextSpan(text: "lbl_sign_up".tr.toUpperCase(), style: CustomTextStyles.bodyLargePrimary.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.left)), SizedBox(height: 27.v), Text("lbl_or".tr, style: CustomTextStyles.headlineSmallLatoBlack90002), SizedBox(height: 29.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlack, child: CustomImageView(imagePath: ImageConstant.imgIcBaselineApple)), Padding(padding: EdgeInsets.only(left: 50.h), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlack, child: CustomImageView(imagePath: ImageConstant.imgGroup47)))]), SizedBox(height: 25.v)])))); } 
/// Section Widget
Widget _buildPhoneNumberSection(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_phone_number".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Selector<SignInProvider, TextEditingController?>(selector: (context, provider) => provider.phoneNumberController, builder: (context, phoneNumberController, child) {return CustomTextFormField(controller: phoneNumberController, hintText: "lbl_44_898907690".tr, hintStyle: theme.textTheme.bodyMedium!);})]); } 
/// Section Widget
Widget _buildPasswordSection(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_password".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Selector<SignInProvider, TextEditingController?>(selector: (context, provider) => provider.passwordController, builder: (context, passwordController, child) {return CustomTextFormField(controller: passwordController, textInputAction: TextInputAction.done, obscureText: true);})]); } 
/// Section Widget
Widget _buildForgotPasswordSection(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Selector<SignInProvider, bool?>(selector: (context, provider) => provider.rememberMe, builder: (context, rememberMe, child) {return CustomCheckboxButton(text: "lbl_remember_me".tr, value: rememberMe, padding: EdgeInsets.symmetric(vertical: 1.v), onChange: (value) {context.read<SignInProvider>().changeCheckBox(value);});}), GestureDetector(onTap: () {onTapTxtForgotPassword(context);}, child: Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_forgot_password".tr, style: CustomTextStyles.bodyMediumBluegray900)))]); } 
/// Navigates to the forgotPaswordScreen when the action is triggered.
onTapTxtForgotPassword(BuildContext context) { NavigatorService.pushNamed(AppRoutes.forgotPaswordScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapSignIn(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapTxtDonthaveanaccount(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpScreen, ); } 
 }
