import 'models/profile_one_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_icon_button.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/profile_one_provider.dart';class ProfileOneScreen extends StatefulWidget {const ProfileOneScreen({Key? key}) : super(key: key);

@override ProfileOneScreenState createState() =>  ProfileOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ProfileOneProvider(), child: ProfileOneScreen()); } 
 }
class ProfileOneScreenState extends State<ProfileOneScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildProfileStack(context), SizedBox(height: 24.v), SizedBox(height: 120.adaptSize, width: 120.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgImage128, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgGroup53, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 5.h, bottom: 2.v))])), SizedBox(height: 60.v), _buildTwentyOneColumn(context), SizedBox(height: 19.v), _buildTwentyOneColumn1(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildProfileStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(bottom: 13.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 21.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 34.v, width: 118.h, text: "lbl_profile".tr, margin: EdgeInsets.only(bottom: 21.v), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapProfile(context);}), Padding(padding: EdgeInsets.only(top: 2.v, right: 10.h, bottom: 21.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillGray, onTap: () {onTapBtnHeaderIcon(context);}, child: CustomImageView(imagePath: ImageConstant.imgHeaderIcon)))])))])); } 
/// Section Widget
Widget _buildTwentyOneColumn(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_name".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Selector<ProfileOneProvider, TextEditingController?>(selector: (context, provider) => provider.nameController, builder: (context, nameController, child) {return CustomTextFormField(controller: nameController, hintText: "lbl_john_doe".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done);})])); } 
/// Section Widget
Widget _buildTwentyOneColumn1(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_date_of_birth".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Container(width: 390.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder22), child: Text("lbl_01_12_1998".tr, style: theme.textTheme.bodyMedium))])); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapProfile(BuildContext context) { NavigatorService.pushNamed(AppRoutes.settingsScreen, ); } 
/// Navigates to the profileScreen when the action is triggered.
onTapBtnHeaderIcon(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
