import 'models/community_two_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_floating_button.dart';import 'provider/community_two_provider.dart';class CommunityTwoScreen extends StatefulWidget {const CommunityTwoScreen({Key? key}) : super(key: key);

@override CommunityTwoScreenState createState() =>  CommunityTwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => CommunityTwoProvider(), child: CommunityTwoScreen()); } 
 }
class CommunityTwoScreenState extends State<CommunityTwoScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildCreatePostStack(context), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_write_post".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 21.v), Container(width: 377.h, margin: EdgeInsets.only(left: 22.h, right: 30.h), child: Text("msg_nullam_turpis_leo".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium)), SizedBox(height: 19.v), _buildCameraColumn(context), SizedBox(height: 19.v)])), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
Widget _buildCreatePostStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 22.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 20.v), CustomElevatedButton(height: 33.v, width: 178.h, text: "lbl_create_post".tr, leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapCreatePost(context);})])))])); } 
/// Section Widget
Widget _buildCameraColumn(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 15.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup1686552776), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup20x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_camera".tr, style: CustomTextStyles.titleMediumGray900))]), SizedBox(height: 28.v), GestureDetector(onTap: () {onTapFrame(context);}, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_add_picture".tr, style: CustomTextStyles.titleMediumGray900))])), SizedBox(height: 29.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup2, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_add_video".tr, style: CustomTextStyles.titleMediumGray900))])])); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 56, width: 56, backgroundColor: theme.colorScheme.primary, child: CustomImageView(imagePath: ImageConstant.imgBellIcon, height: 28.0.v, width: 28.0.h)); } 
/// Navigates to the communityOneContainerScreen when the action is triggered.
onTapCreatePost(BuildContext context) { NavigatorService.pushNamed(AppRoutes.communityOneContainerScreen, ); } 
/// Navigates to the communityScreen when the action is triggered.
onTapFrame(BuildContext context) { NavigatorService.pushNamed(AppRoutes.communityScreen, ); } 
 }
