import 'models/delete_account_model.dart';import 'package:flutter/material.dart';import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/app_bar/appbar_title_button_one.dart';import 'package:nofapp/widgets/app_bar/custom_app_bar.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/delete_account_provider.dart';class DeleteAccountScreen extends StatefulWidget {const DeleteAccountScreen({Key? key}) : super(key: key);

@override DeleteAccountScreenState createState() =>  DeleteAccountScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => DeleteAccountProvider(), child: DeleteAccountScreen()); } 
 }
class DeleteAccountScreenState extends State<DeleteAccountScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 10.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 116.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgFrame1686552773, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 9.v)), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_delete_your_account".tr, style: CustomTextStyles.titleLargeRed900))])), SizedBox(height: 21.v), Container(width: 383.h, margin: EdgeInsets.only(right: 6.h), child: Text("msg_we_re_sorry_to_see".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray9000215)), SizedBox(height: 16.v), Container(width: 370.h, margin: EdgeInsets.only(right: 19.h), child: Text("msg_if_you_re_having".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray9000215)), SizedBox(height: 21.v), Container(width: 366.h, margin: EdgeInsets.only(right: 23.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_to".tr, style: CustomTextStyles.bodyLargeBluegray90002), TextSpan(text: "lbl_delete".tr, style: CustomTextStyles.bodyLargeRed900), TextSpan(text: "msg_your_account_confirm".tr, style: CustomTextStyles.bodyLargeBluegray90002)]), textAlign: TextAlign.left)), SizedBox(height: 20.v), _buildTwentyOne(context), SizedBox(height: 25.v), _buildTickSquare(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildDeleteAccountButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(title: AppbarTitleButtonOne(margin: EdgeInsets.only(left: 20.h), onTap: () {onTapDeleteAccount(context);})); } 
/// Section Widget
Widget _buildTwentyOne(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_password".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Selector<DeleteAccountProvider, TextEditingController?>(selector: (context, provider) => provider.passwordController, builder: (context, passwordController, child) {return CustomTextFormField(controller: passwordController, textInputAction: TextInputAction.done, obscureText: true);})]); } 
/// Section Widget
Widget _buildTickSquare(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 42.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTickSquareBlueGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 26.v)), Expanded(child: Container(width: 317.h, margin: EdgeInsets.only(left: 6.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_by_tapping_confirm2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "msg_terms_of_service".tr, style: CustomTextStyles.bodyMediumPrimary), TextSpan(text: "lbl_and".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "lbl_privacy_policy2".tr, style: CustomTextStyles.bodyMediumPrimary), TextSpan(text: "lbl_of_app_name".tr, style: theme.textTheme.bodyMedium)]), textAlign: TextAlign.left)))])); } 
/// Section Widget
Widget _buildDeleteAccountButton(BuildContext context) { return CustomElevatedButton(text: "lbl_delete_account".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 48.v), onPressed: () {onTapDeleteAccountButton(context);}); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapDeleteAccount(BuildContext context) { NavigatorService.pushNamed(AppRoutes.settingsScreen, ); } 
/// Navigates to the deleteAccountOneScreen when the action is triggered.
onTapDeleteAccountButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.deleteAccountOneScreen, ); } 
 }
