import 'models/experience_encounter_tips_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'provider/experience_encounter_tips_provider.dart';class ExperienceEncounterTipsScreen extends StatefulWidget {const ExperienceEncounterTipsScreen({Key? key}) : super(key: key);

@override ExperienceEncounterTipsScreenState createState() =>  ExperienceEncounterTipsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ExperienceEncounterTipsProvider(), child: ExperienceEncounterTipsScreen()); } 
 }
class ExperienceEncounterTipsScreenState extends State<ExperienceEncounterTipsScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildExperienceEncounterStack(context), SizedBox(height: 24.v), CustomImageView(imagePath: ImageConstant.imgRectangle148333, height: 185.v, width: 390.h, radius: BorderRadius.circular(20.h)), SizedBox(height: 20.v), _buildFrameRow(context), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_explanation_of_this".tr, style: CustomTextStyles.titleMediumBluegray900SemiBold))), SizedBox(height: 11.v), Container(width: 387.h, margin: EdgeInsets.only(left: 20.h, right: 23.h), child: Text("msg_this_is_the_most".tr, maxLines: 14, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge)), Spacer(flex: 17), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("msg_experience_encounter3".tr, style: CustomTextStyles.titleMediumBluegray900SemiBold))), Spacer(flex: 18), Container(width: 387.h, margin: EdgeInsets.only(left: 20.h, right: 23.h), child: Text("msg_intense_urges_temptations".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge)), Spacer(flex: 31), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_some_tips".tr, style: CustomTextStyles.titleMediumBluegray900SemiBold))), Spacer(flex: 32), SizedBox(height: 44.v), Container(width: 390.h, margin: EdgeInsets.symmetric(horizontal: 20.h), child: Text("msg_completely_avoid".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 2.06)))])))); } 
/// Section Widget
Widget _buildExperienceEncounterStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 24.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 17.v), CustomElevatedButton(height: 33.v, text: "msg_experience_encounter2".tr, margin: EdgeInsets.only(right: 27.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapExperienceEncounterTips(context);})])))])); } 
/// Section Widget
Widget _buildFrameRow(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 20.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.outlineGrayE.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Row(mainAxisSize: MainAxisSize.max, children: [Container(height: 70.adaptSize, width: 70.adaptSize, padding: EdgeInsets.all(10.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder35), child: CustomImageView(imagePath: ImageConstant.imgSandClock1, height: 50.adaptSize, width: 50.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 20.h, top: 20.v, bottom: 19.v), child: Text("msg_phase_1_0_2_days".tr, style: CustomTextStyles.titleLargeBluegray900))])); } 
/// Navigates to the homeScreen when the action is triggered.
onTapExperienceEncounterTips(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
