import 'models/daily_task_two_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/daily_task_two_provider.dart';import 'package:nofapp/presentation/daily_task_one_dialog/daily_task_one_dialog.dart';class DailyTaskTwoScreen extends StatefulWidget {const DailyTaskTwoScreen({Key? key}) : super(key: key);

@override DailyTaskTwoScreenState createState() =>  DailyTaskTwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => DailyTaskTwoProvider(), child: DailyTaskTwoScreen()); } 
 }
class DailyTaskTwoScreenState extends State<DailyTaskTwoScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildAddTaskStack(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Container(width: 367.h, margin: EdgeInsets.only(left: 20.h, right: 42.h), child: Text("msg_lorem_ipsum_dolor6".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))), SizedBox(height: 20.v), _buildTaskForm(context), Spacer(flex: 28), CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.symmetric(horizontal: 20.h), onPressed: () {onTapAdd(context);}), Spacer(flex: 71)])))); } 
/// Section Widget
Widget _buildAddTaskStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 22.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 20.v), CustomElevatedButton(height: 33.v, width: 152.h, text: "lbl_add_task".tr, leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapAddTask(context);})])))])); } 
/// Section Widget
Widget _buildTaskForm(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_add_task".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), Selector<DailyTaskTwoProvider, TextEditingController?>(selector: (context, provider) => provider.taskController, builder: (context, taskController, child) {return CustomTextFormField(controller: taskController, hintText: "lbl_do_10_push_ups".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done);})])); } 
/// Navigates to the dailyTaskThreeScreen when the action is triggered.
onTapAddTask(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dailyTaskThreeScreen, ); } 

/// Displays a dialog with the [DailyTaskOneDialog] content.
onTapAdd(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: DailyTaskOneDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
