import 'models/generate_code_three_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_pin_code_text_field.dart';import 'provider/generate_code_three_provider.dart';import 'package:nofapp/presentation/generate_code_dialog/generate_code_dialog.dart';class GenerateCodeThreeScreen extends StatefulWidget {const GenerateCodeThreeScreen({Key? key}) : super(key: key);

@override GenerateCodeThreeScreenState createState() =>  GenerateCodeThreeScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => GenerateCodeThreeProvider(), child: GenerateCodeThreeScreen()); } 
 }
class GenerateCodeThreeScreenState extends State<GenerateCodeThreeScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildGenerateCodeStack(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Container(width: 367.h, margin: EdgeInsets.only(left: 20.h, right: 42.h), child: Text("msg_lorem_ipsum_dolor6".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))), SizedBox(height: 49.v), Padding(padding: EdgeInsets.symmetric(horizontal: 95.h), child: Selector<GenerateCodeThreeProvider, TextEditingController?>(selector: (context, provider) => provider.otpController, builder: (context, otpController, child) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), Spacer(flex: 29), CustomElevatedButton(text: "lbl_generate".tr, margin: EdgeInsets.symmetric(horizontal: 20.h), onPressed: () {onTapGenerate(context);}), Spacer(flex: 70)])))); } 
/// Section Widget
Widget _buildGenerateCodeStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 22.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 20.v), CustomElevatedButton(height: 33.v, width: 217.h, text: "lbl_generate_code".tr, leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapGenerateCode(context);})])))])); } 
/// Navigates to the homeScreen when the action is triggered.
onTapGenerateCode(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 

/// Displays a dialog with the [GenerateCodeDialog] content.
onTapGenerate(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: GenerateCodeDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
