import 'models/profile_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:nofapp/core/app_export.dart';import 'package:nofapp/widgets/custom_elevated_button.dart';import 'package:nofapp/widgets/custom_text_form_field.dart';import 'provider/profile_provider.dart';class ProfileScreen extends StatefulWidget {const ProfileScreen({Key? key}) : super(key: key);

@override ProfileScreenState createState() =>  ProfileScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ProfileProvider(), child: ProfileScreen()); } 
 }
class ProfileScreenState extends State<ProfileScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildProfileStack(context), SizedBox(height: 24.v), SizedBox(height: 120.adaptSize, width: 120.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgImage128, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgGroup53, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 5.h, bottom: 2.v))])), SizedBox(height: 59.v), _buildPersonalInfoColumn(context), SizedBox(height: 19.v), _buildDateOfBirthColumn(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSaveChangesButton(context))); } 
/// Section Widget
Widget _buildProfileStack(BuildContext context) { return SizedBox(height: 112.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector2, height: 112.v, width: 430.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 21.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup147), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 21.v), CustomElevatedButton(height: 34.v, width: 118.h, text: "lbl_profile".tr, leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgBackButton, height: 32.adaptSize, width: 32.adaptSize)), buttonStyle: CustomButtonStyles.none, buttonTextStyle: theme.textTheme.titleLarge!, onPressed: () {onTapProfile(context);})])))])); } 
/// Section Widget
Widget _buildPersonalInfoColumn(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_first_name".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Selector<ProfileProvider, TextEditingController?>(selector: (context, provider) => provider.firstNameController, builder: (context, firstNameController, child) {return CustomTextFormField(controller: firstNameController, hintText: "lbl_john_doe".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done);})])); } 
/// Section Widget
Widget _buildDateOfBirthColumn(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_date_of_birth".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Container(width: 390.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 11.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder22), child: Text("lbl_01_12_1998".tr, style: theme.textTheme.bodyMedium))])); } 
/// Section Widget
Widget _buildSaveChangesButton(BuildContext context) { return CustomElevatedButton(text: "lbl_save_changes".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 48.v), onPressed: () {onTapSaveChangesButton(context);}); } 
/// Navigates to the profileOneScreen when the action is triggered.
onTapProfile(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileOneScreen, ); } 
/// Navigates to the profileOneScreen when the action is triggered.
onTapSaveChangesButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileOneScreen, ); } 
 }
